site_name: American Policy Architecture Institute
site_description: A portfolio of civic systems maintenance proposals
site_author: Albert Ramos
copyright: Â© 2026 Albert Ramos | American Policy Architecture Institute
site_url: https://policyarchitecture.org

theme:
  name: material
  palette:
    # Light Mode
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark Mode
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - search.highlight
    # - toc.integrate

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md

  - Congress & Elections:
      - Congressional Modernization Act:
          - One-Page Summary: congress/cma/CMA-One-Page-Summary.md
          - Legislative Text: congress/cma/CMA-The-Congressional-Modernization-Act.md
          - Policy Rationale: congress/cma/CMA-Policy-Rationale.md
          - Reference Materials:
              - What Changes For Voters: congress/cma/CMA-What-Changes-For-Voters.md
              - Sample Ballot (Multi-Member District): congress/cma/CMA-Sample-Ballot-Multi-Member-District.md
              - Sample Ballot (Single-Member District): congress/cma/CMA-Sample-Ballot-Single-Member-District.md
              - House Member Guide: congress/cma/CMA-House-Member-Guide.md
              - Data Appendix: congress/cma/CMA-House-Member-Guide-Data-Appendix.md

  - Economic Stability & Security:
      - American Shared Prosperity Compact:
          - One-Page Summary: aspc/ASPC-One-Page-Summary.md
          - Executive Summary: aspc/ASPC-Executive-Summary.md
          - FAQ: aspc/ASPC-FAQ.md
      - American Prosperity and Stability Act:
          - One-Page Summary: aspc/APSA-One-Page-Summary.md
          - Legislative Text: aspc/APSA-Legislative-Text.md
          - Policy Rationale: aspc/APSA-Policy-Rationale.md
      - American Payment Network Act:
          - One-Page Summary: aspc/APNA-One-Page-Summary.md
          - Legislative Text: aspc/APNA-Legislative-Text.md
          - Policy Rationale: aspc/APNA-Policy-Rationale.md
      - Secure Our Children Act:
          - One-Page Summary: aspc/SOCA-One-Page-Summary.md
          - Legislative Text: aspc/SOCA-Legislative-Text.md
          - Policy Rationale: aspc/SOCA-Policy-Rationale.md

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - tables
  - admonition
  - def_list

plugins:
  - search
