site_name: American Policy Architecture Institute
site_description: A portfolio of civic systems maintenance proposals
site_author: Albert Ramos
copyright: "&copy; 2026 Albert Ramos | American Policy Architecture Institute"
site_url: https://policyarchitecture.org

theme:
    name: material
    palette:
        # Light Mode
        - scheme: default
          primary: indigo
          accent: amber
          toggle:
              icon: material/brightness-7
              name: Switch to dark mode
        # Dark Mode
        - scheme: slate
          primary: indigo
          accent: amber
          toggle:
              icon: material/brightness-4
              name: Switch to light mode
    features:
        - navigation.sections
        - search.highlight

extra_css:
    - stylesheets/extra.css

nav:
    - Home: index.md

    - Congress & Elections:
          - Congressional Modernization Framework:
                - Introduction: congress/cmf/introduction.md
                - Integration Analysis: congress/cmf/integration-analysis.md
                - Federal Elections Modernization Act:
                      - Introduction: congress/cmf/fema/introduction.md
                      - Overview: congress/cmf/fema/overview.md
                      - Legislative Text: congress/cmf/fema/legislative-text.md
                      - Policy Rationale: congress/cmf/fema/policy-rationale.md
                      - Reference Materials:
                            - What Changes For Voters: congress/cmf/fema/what-changes-for-voters.md
                            - Sample Ballot (Multi-Member District): congress/cmf/fema/sample-mmd-ballot-12-candidates.md
                            - Sample Ballot (Single-Member District): congress/cmf/fema/sample-smd-ballot-9-candidates.md
                            - House Member Guide: congress/cmf/fema/house-member-guide.md
                            - Voting Methods Explainer: congress/cmf/fema/voting-methods-technical-explainer.md
                            - FCAO Explainer: congress/cmf/fema/fcao-explainer.md
                            - Constitutional Authority Memorandum: congress/cmf/fema/constitutional-authority-technical-memorandum.md
                            - Constitutional Boundaries of PR: congress/cmf/fema/constitutional-boundaries-of-proportional-representation.md
                - Office of Congressional Procedure Act:
                      - Introduction: congress/cmf/ocp/introduction.md
                      - Overview: congress/cmf/ocp/overview.md
                      - Legislative Text: congress/cmf/ocp/legislative-text.md
                      - Policy Rationale: congress/cmf/ocp/policy-rationale.md
                      - Reference Materials:
                            - Constitutional Analysis: congress/cmf/ocp/constitutional-analysis.md
          - Congressional Capacity Commission Act:
                - Introduction: congress/ccc/introduction.md
                - Overview: congress/ccc/overview.md
                - Legislative Text: congress/ccc/legislative-text.md
                - Policy Rationale: congress/ccc/policy-rationale.md
                - Reference Materials:
                      - Implementation Timeline: congress/ccc/implementation-timeline.md
          - Candidate Verification and Transparency Act:
                - Introduction: congress/cvta/introduction.md
                - Overview: congress/cvta/overview.md
                - Legislative Text: congress/cvta/legislative-text.md
                - Policy Rationale: congress/cvta/policy-rationale.md
                - Reference Materials:
                      - Implementation Timeline: congress/cvta/implementation-timeline.md

    - Executive Branch:
          - Civil Service Accountability Act:
                - Introduction: executive/csaa/introduction.md
                - Future State Analysis: executive/csaa/future-state-analysis.md
                - Overview: executive/csaa/overview.md
                - Legislative Text: executive/csaa/legislative-text.md
                - Policy Rationale: executive/csaa/policy-rationale.md
                - Reference Materials:
                      - International Comparative Analysis: executive/csaa/international-comparison.md
                      - Constitutional and Legal Analysis: executive/csaa/constitutional-analysis.md
                      - Economic Analysis: executive/csaa/economic-analysis.md
                      - CMF Interaction Analysis: executive/csaa/laying-the-groundwork.md

    - Federal Judiciary:
          - Federal Judicial Balance and Accountability Act:
                - Introduction: judiciary/fjbaa/introduction.md
                - Overview: judiciary/fjbaa/overview.md
                - Legislative Text: judiciary/fjbaa/legislative-text.md
                - Circuit Maps: judiciary/fjbaa/circuit-maps.md
                - Policy Rationale: judiciary/fjbaa/policy-rationale.md
                - Reference Materials:
                      - Legal Analysis: judiciary/fjbaa/legal-analysis.md
                      - Foundational Principles: judiciary/fjbaa/foundational-principles.md
                      - Implementation Timeline: judiciary/fjbaa/implementation-timeline.md
                      - Emergent Benefits of Principled Design: judiciary/fjbaa/emergent-benefits-of-principled-design.md
                - Position Papers:
                      - The Case for Twelve-Year Active Service: judiciary/fjbaa/the-case-for-twelve-years.md

    - Economic Stability & Security:
          - American Shared Prosperity Compact:
                - Introduction: aspc/introduction.md
                - Overview: aspc/overview.md
                - Integration and Sequencing Guide: aspc/integration-and-sequencing-guide.md
                - FAQ: aspc/frequently-asked-questions.md
                - American Prosperity and Stability Act:
                      - Introduction: aspc/apsa/introduction.md
                      - Overview: aspc/apsa/overview.md
                      - Legislative Text: aspc/apsa/legislative-text.md
                      - Policy Rationale: aspc/apsa/policy-rationale.md
                      - Reference Materials:
                            - Future State Analysis: aspc/apsa/future-state-analysis.md
                            - Implementation Timeline: aspc/apsa/implementation-timeline.md
                            - Constituency Impact Analysis: aspc/apsa/constituency-impact-analysis.md
                - American Payment Network Act:
                      - Introduction: aspc/apna/introduction.md
                      - Overview: aspc/apna/overview.md
                      - Legislative Text: aspc/apna/legislative-text.md
                      - Policy Rationale: aspc/apna/policy-rationale.md
                      - Reference Materials:
                            - Future State Analysis: aspc/apna/future-state-analysis.md
                            - Implementation Timeline: aspc/apna/implementation-timeline.md
                            - Constituency Impact Analysis: aspc/apna/constituency-impact-analysis.md
                - Secure Our Children Act:
                     - Introduction: aspc/soca/introduction.md
                     - Overview: aspc/soca/overview.md
                     - Legislative Text: aspc/soca/legislative-text.md
                     - Policy Rationale: aspc/soca/policy-rationale.md
                     - Reference Materials:
                           - Implementation Timeline: aspc/soca/implementation-timeline.md
                           - Constituency Impact Analysis: aspc/soca/constituency-impact-analysis.md
                - Comparative Analysis:
                    - ASPC vs. EDAA: aspc/comparative-analysis-edaa.md

markdown_extensions:
    - toc:
          permalink: true
          toc_depth: 4
    - tables
    - admonition
    - def_list

plugins:
    - search

extra:
    analytics:
        provider: google
        property: G-TQH8Q7DDKZ
